# Generated by Django 5.0.6 on 2024-05-15 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('comparison_operator', models.CharField(choices=[('<', '<'), ('>', '>'), ('<=', '<='), ('>=', '>='), ('==', '==')], max_length=2)),
                ('value', models.FloatField()),
                ('frequency', models.CharField(choices=[('day', 'Day'), ('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('is_statisfied', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
